library(pkgload)
load_all('.')
example_dir <- normalizePath(file.path('examples', 'SCOPUS_POWER_SYSTEMS_FREQUENCY_ESTIMATOR'))
source_file <- normalizePath(file.path(example_dir, 'data', 'scopus.bib'))
out_dir <- file.path(example_dir, 'results_codex_full_v2')
if (dir.exists(out_dir)) unlink(out_dir, recursive = TRUE, force = TRUE)
config <- biblio_config(output_dir = out_dir, export = TRUE, validate_strict = FALSE, top_n_countries = 15, top_n_authors = 15, top_n_sources = 15)
sources <- list(scopus = list(file = source_file, db = 'scopus', format = 'bibtex', role = 'database'))
m0 <- run_m0(sources = sources, config = config, prisma_spec = 'auto', export = TRUE)
bib_data <- m0_get_bib_data(m0)
m1 <- run_m1(bib_data, config = config, export = TRUE)
annual_df <- m0_get(m0, 'annual')
m2 <- run_m2(annual_df, config = config, export = TRUE)
m3 <- run_m3(bib_data, config = config, export = TRUE)
cat('DONE\n')
