library(extrafont)

font_import()  


# ---------------------------------------------------------------------------- #
# Function: Generate Report for Document Types Analysis
# ---------------------------------------------------------------------------- #
fn_m1_mtrc1_generate_document_types_report <- function(v_document_types) {
  # Ensure the output directory exists
  report_dir <- "results/M1_Main_Information/reports"
  if (!dir.exists(report_dir)) {
    dir.create(report_dir, recursive = TRUE)
  }

  # Create a data frame for document types
  df <- data.frame(
    Document_Type = names(v_document_types),
    Count = sapply(v_document_types, function(x) ifelse(length(x) == 0, 0, x))
  )

  # Filter out document types with zero count and apply label mapping
  df <- df[df$Count > 0, ]
  df$Document_Type <- LABEL_MAPPING[df$Document_Type]

  # Sort the data by count in descending order
  df <- df[order(-df$Count), ]

  # Calculate percentages
  total_count <- sum(df$Count)
  df$Percentage <- round((df$Count / total_count) * 100, 2)

  # Generate a plain text report
  txt_report <- paste0(
    "Document Types Distribution Report\n",
    "==================================\n\n",
    "Total Articles: ", total_count, "\n\n",
    "Breakdown by Document Type:\n\n",
    paste(
      sprintf(
        "%-20s: %d (%.2f%%)", 
        df$Document_Type, df$Count, df$Percentage
      ),
      collapse = "\n"
    ),
    "\n\nGenerated by fn_m1_mtrc1_generate_document_types_report"
  )

  # Save the plain text report
  txt_file_path <- file.path(report_dir, "M1_Document_Types_Report.txt")
  writeLines(txt_report, txt_file_path)

  # Generate a LaTeX report
  tex_report <- paste0(
    "\\documentclass[12pt]{article}\n",
    "\\usepackage{geometry}\n",
    "\\usepackage{graphicx}\n",
    "\\geometry{a4paper, margin=1in}\n",
    "\\begin{document}\n",
    "\\title{Document Types Distribution Report}\n",
    "\\author{}\n",
    "\\date{\\today}\n",
    "\\maketitle\n",
    "\\section*{Overview}\n",
    "This report summarizes the distribution of document types in the dataset.\n",
    "The total number of articles analyzed is \\textbf{", total_count, "}.\n\n",
    "\\section*{Breakdown by Document Type}\n",
    "\\begin{itemize}\n",
    paste(
      sprintf(
        "\\item \\textbf{%s}: %d (%.2f\\%%)", 
        df$Document_Type, df$Count, df$Percentage
      ),
      collapse = "\n"
    ),
    "\n\\end{itemize}\n\n",
    "\\section*{Visualization}\n",
    "The distribution of document types is visualized in the accompanying pie chart.\n",
    "\\includegraphics[width=0.8\\textwidth]{../figures/M1_G2_DOCUMENT_TYPES_PIE_PLOT_PNG.png}\n",
    "\\end{document}"
  )

  # Save the LaTeX report
  tex_file_path <- file.path(report_dir, "M1_Document_Types_Report.tex")
  writeLines(tex_report, tex_file_path)

  # Log success
  message("[INFO] Document types reports generated successfully:")
  message("  - Plain text report: ", txt_file_path)
  message("  - LaTeX report: ", tex_file_path)
}
library(glue)

generate_document_types_report <- function(df, output_path) {
  # Ensure percentages are calculated
  total_count <- sum(df$Count)
  df$Percentage <- (df$Count / total_count) * 100
  
  # Determine key insights
  dominant_type <- df$Document_Type[which.max(df$Percentage)]
  dominant_percentage <- max(df$Percentage)
  evenly_distributed <- all(df$Percentage < 40) # No type has more than 40%

  # Generate conclusions dynamically
  if (dominant_percentage > 50) {
    conclusions <- glue(
      "The analysis reveals that the document type \\textbf{{{dominant_type}}} dominates the dataset, ",
      "representing \\textbf{{{round(dominant_percentage, 2)}}}\\% of all articles. ",
      "This suggests that most articles in this collection are focused on this specific type."
    )
  } else if (evenly_distributed) {
    conclusions <- glue(
      "The dataset shows an even distribution of document types, with no single type exceeding 40\\% of the total. ",
      "This indicates a diverse set of article formats in the collection."
    )
  } else {
    conclusions <- glue(
      "The document types are varied, with \\textbf{{{dominant_type}}} being the most common, ",
      "accounting for \\textbf{{{round(dominant_percentage, 2)}}}\\% of the total. ",
      "Other document types contribute significantly as well, indicating a balanced dataset."
    )
  }

  # Create LaTeX content
  latex_template <- "
\\documentclass[12pt]{article}
\\usepackage{geometry}
\\usepackage{graphicx}
\\geometry{a4paper, margin=1in}
\\begin{document}
\\title{Document Types Distribution Report}
\\author{}
\\date{\\today}
\\maketitle
\\section*{Overview}
The total number of articles analyzed is \\textbf{{{total_count}}}.
\\section*{Breakdown by Document Type}
\\begin{itemize}
{item_list}
\\end{itemize}
\\section*{Conclusions}
{conclusions}
\\section*{Visualization}
The distribution of document types is visualized in the accompanying pie chart:
\\includegraphics[width=0.8\\textwidth]{../figures/M1_G2_DOCUMENT_TYPES_PIE_PLOT_PNG.png}
\\end{document}
  "

  # Generate item list for LaTeX
  item_list <- paste(
    glue("\\item \\textbf{{{df$Document_Type}}}: {df$Count} ({round(df$Percentage, 2)}\\%)"),
    collapse = "\n"
  )

  # Fill the template with content
  content <- glue(latex_template,
                  total_count = total_count,
                  item_list = item_list,
                  conclusions = conclusions
  )

  # Save the LaTeX file
  writeLines(content, output_path)
}









plot_dual_axis_bar_chart <- function(most_prod_countries, tc_per_country) {
  tryCatch({
    # Step 1: Combine Data
    message("[DEBUG] Combining data...")
    combined_data <- merge(most_prod_countries, tc_per_country, by = "Country", all = TRUE) %>%
      mutate(
        Articles = suppressWarnings(as.numeric(Articles)),
        `Total Citations` = suppressWarnings(as.numeric(`Total Citations`))
      )

    # Step 2: Check for Missing or Invalid Data
    if (any(is.na(combined_data$Articles)) || any(is.na(combined_data$`Total Citations`))) {
      message("[INFO] Removing rows with NA in 'Articles' or 'Total Citations'.")
      combined_data <- combined_data[complete.cases(combined_data[, c("Articles", "Total Citations")]), ]
    }

    # Ensure there is valid data
    if (nrow(combined_data) == 0) {
      stop("[ERROR] No valid data available for plotting after cleaning.")
    }

    # Step 3: Reshape Data
    message("[DEBUG] Reshaping data for plotting...")
    combined_long <- combined_data %>%
      pivot_longer(cols = c(Articles, `Total Citations`), names_to = "Metric", values_to = "Value") %>%
      mutate(Value = suppressWarnings(as.numeric(Value)))


    # Check for Invalid Values
    if (any(is.na(combined_long$Value))) {
      message("[INFO] Removing rows with NA in 'Value' column.")
      combined_long <- combined_long[!is.na(combined_long$Value), ]
    }

    # Ensure there is valid data to plot
    if (nrow(combined_long) == 0) {
      stop("[ERROR] No valid data available for plotting after reshaping.")
    }

    # Step 4: Define Colors for the Metrics
    metric_colors <- c("Articles" = THEME_COLORS$Main[1], "Total Citations" = THEME_COLORS$Main[2])

    # Step 5: Create Dual-axis Bar Chart
    message("[DEBUG] Creating dual-axis bar chart...")
    dual_bar_chart <- ggplot(combined_long, aes(x = reorder(Country, -Value), y = Value, fill = Metric)) +
      geom_bar(stat = "identity", position = "dodge", width = 0.7) +
      scale_fill_manual(values = metric_colors) +
      labs(
        title = "Comparison of Productivity and Total Citations",
        x = "Country",
        y = "Value"
      ) +
      theme_minimal() +
      theme(
        plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title = element_text(size = 12),
        legend.title = element_blank(),
        legend.position = "top"
      )

    # Debug: Validate Plot Object
    if (!inherits(dual_bar_chart, "ggplot")) {
      stop("[ERROR] Generated object is not a valid ggplot object.")
    } else {
      message("[DEBUG] Dual-axis bar chart object created successfully.")
    }

    # Step 6: Save Plot
    message("[DEBUG] Saving dual-axis bar chart...")
    save_plot(dual_bar_chart, "PT_3_Comparison_Productivity_vs_Impact_Bar_Chart", width = 10, height = 6, dpi = 300)

    # Step 7: Save Insights
    insight <- "This chart highlights which countries have a balance or imbalance between their productivity and total citations."
    write(insight, file = "results/Comparison_Productivity_vs_Impact_Insights.txt")

    message("[INFO] Dual-axis bar chart created successfully.")
    return(dual_bar_chart)
  }, error = function(e) {
    message("[ERROR] Failed to create dual-axis bar chart: ", e$message)
    return(NULL)
  })
}




# Function 3: Lorenz Curve Overlay
plot_lorenz_curve_overlay <- function(most_prod_countries, tc_per_country) {
  # Combine data
  combined_data <- merge(most_prod_countries, tc_per_country, by = "Country") %>%
    mutate(
      Articles = as.numeric(Articles),               # Ensure Articles is numeric
      `Total Citations` = as.numeric(`Total Citations`) # Ensure Total Citations is numeric
    ) %>%
    arrange(desc(Articles)) %>%
    mutate(
      CumArticles = cumsum(Articles) / sum(Articles),
      CumCitations = cumsum(`Total Citations`) / sum(`Total Citations`),
      CountryRank = row_number() / n()
    )

  # Create Lorenz curve
  lorenz_curve <- ggplot(combined_data) +
    geom_line(aes(x = CountryRank, y = CumArticles, color = "Articles"), linewidth = 1) +
    geom_line(aes(x = CountryRank, y = CumCitations, color = "Citations"), linewidth = 1) +
    scale_color_manual(values = c("Articles" = "#1b9e77", "Citations" = "#d95f02")) +
    labs(
      title = "Lorenz Curve: Articles vs. Citations",
      x = "Cumulative Proportion of Countries",
      y = "Cumulative Proportion of Metric"
    ) +
    theme_minimal() +
    theme(
      plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
      legend.position = "right"
    )

  # Save plot
  save_plot("PT_3_Lorenz_Curve_Comparison", lorenz_curve, width = 10, height = 6, dpi = 300)

  # Save insights
  insight <- "The Lorenz curve shows whether citations are more or less equally distributed than the number of articles among countries."
  write(insight, file = "results/Lorenz_Curve_Insights.txt")

  return(lorenz_curve)
}


# Function 4: Treemap with Combined Metrics
plot_combined_treemap <- function(most_prod_countries, tc_per_country) {
  # Combine data
  combined_data <- merge(most_prod_countries, tc_per_country, by = "Country")

  # Create treemap
  combined_treemap <- ggplot(combined_data, aes(
    area = Articles,
    fill = `Total Citations`,
    label = paste(Country, "\nArticles:", Articles, "\nCitations:", `Total Citations`)
  )) +
    geom_treemap() +
    geom_treemap_text(fontface = "bold", colour = "white", place = "centre", grow = TRUE) +
    scale_fill_viridis_c(option = "plasma", name = "Total Citations") +
    labs(
      title = "Treemap: Articles vs. Citations",
      fill = "Total Citations"
    ) +
    theme_minimal() +
    theme(
      plot.title = element_text(size = 16, face = "bold", hjust = 0.5)
    )

  # Save plot
  save_plot("PT_3_Treemap_Articles_vs_Citations", combined_treemap, width = 10, height = 6, dpi = 300)

  # Save insights
  insight <- "The treemap visually combines productivity and impact, with area representing articles and color intensity representing citations."
  write(insight, file = "results/Treemap_Insights.txt")

  return(combined_treemap)
}
