# ============================================================================
# zzz_check_globals.R - R CMD check namespace hygiene for NSE-heavy modules
# ============================================================================

utils::globalVariables(c(
  "%>%", ".", "ACF", "AIC", "AU", "Articles", "Authors", "BIC", "Box.test",
  "CUSUM", "Collaborations", "CompositeScore", "Composite_Rank", "DI", "DT",
  "Dimension", "Fitted", "Forecast", "Frequency", "Highlight", "Institution1",
  "Institution2", "Lag", "Lower", "M0_DOC_ID", "MAE", "Metric", "Model",
  "New", "Countries", "PACF", "PC1", "PC2", "PY", "Percentage", "Period",
  "Power", "Predicted", "R2", "Residual", "ResidualSq", "SO", "StdResidual",
  "Std_Resid", "TC", "TI", "Total_Collaborations", "Type", "Upper", "Value",
  "Weight", "Window", "Year", "acf", "adist", "affiliation_id",
  "affiliation_raw", "after_stat", "age_normalized_citations", "aggregate",
  "anova", "ar", "article_count", "articles", "as.formula", "author",
  "author_label", "author_position", "author_rank", "ave",
  "average_citations", "avg_citations", "avg_production", "avg_rank",
  "avg_tc", "build_m5_manifest", "build_m6_manifest", "cagr",
  "capture.output", "career_length", "career_stage", "category", "change",
  "change_point_year", "checkpoint", "chisq.test", "citations", "cited_count",
  "citing_documents", "city", "cluster", "cluster_id", "cluster_label",
  "cluster_label_short", "cluster_tag", "cluster_type", "coef",
  "coefficient", "collaboration_rate", "colorRampPalette", "combn",
  "community", "complete.cases", "completed", "component", "composite_rank",
  "consensus_decision", "continent", "cor", "cor.test", "count", "country",
  "country_1", "country_2", "cum_share", "cumsum_papers", "cumsum_pct",
  "cumulative", "cumulative_articles_pct", "cumulative_citations",
  "cumulative_entities", "cumulative_share", "cumulative_value",
  "cumulative_values", "cusum_sq_critical_upper", "cutree", "data",
  "decision", "decision_date", "density", "department", "desc", "dexp",
  "direction", "dist", "distribution", "dlnorm", "dnorm", "doc_id", "doi",
  "dweibull", "end_value", "end_year", "evidence_class", "export_m5",
  "export_m6", "facet_term", "fft", "fill", "fill_value", "first_share",
  "fitted", "flush.console", "fold", "freq", "frequency", "from_x", "from_y",
  "funding_type", "funding_value", "g_index", "gdp_usd", "geography_rank",
  "gi_star", "gini", "group", "growth_rate", "growth_rate_last_year", "h",
  "h_index", "hclust", "hdi", "head", "height", "highlight", "hjust",
  "hypothesis", "impact_median", "index_label", "inst1", "inst2", "inst_pct",
  "install.packages", "institution", "institution_canonical",
  "institution_clean", "institution_short", "keyword", "keyword1",
  "keyword2", "keyword_norm", "keyword_raw", "keyword_type", "kmeans",
  "ks.test", "label", "label_clean", "label_text", "lag", "last_share",
  "ledger_id", "lm", "logLik", "log_authors", "log_n", "lower",
  "m5_render_all", "m6_render_all", "mae", "mcp", "mcp_doc", "mcp_pct",
  "mcp_ratio", "mean_citations", "median", "median_velocity", "method",
  "metric", "model", "momentum_score", "n", "n_articles", "n_authors",
  "n_citations", "n_cities", "n_collaborations", "n_collaborators",
  "n_countries", "n_documents", "n_institutions", "n_keywords", "n_papers",
  "n_years", "na.exclude", "na.omit", "name", "new_countries", "nls",
  "nls.control", "normalized_power", "optimize", "outcome", "output_median",
  "p.adjust", "p_value", "pacf", "pair", "paper_rank", "pchisq", "pct",
  "pct_label", "pct_of_total", "period", "period_label", "pf", "phase",
  "pnorm", "poly", "position", "power", "prcomp", "predict", "prevalence",
  "prior_mean", "probability", "production", "prop_pop", "prop_value",
  "proportion", "pt", "qf", "qnorm", "qt", "quadrant", "quantile",
  "rank_change", "rank_first", "rank_last", "rank_pct", "ranking_score",
  "reason", "recent_mean", "reference_authors", "reference_doi",
  "reference_journal", "reference_year", "region", "reorder", "reshape",
  "resid", "residuals", "result", "result_color", "result_label", "reviewer",
  "rnorm", "rstandard", "runif", "salton", "scp", "scp_doc", "sd", "sector",
  "sector1", "sector2", "setNames", "shapiro.test", "share", "significance",
  "slope", "source_clean", "source_db", "source_tag", "stage", "start_value",
  "start_year", "state", "status", "stl", "stratum", "strength", "t.test",
  "tail", "target", "theoretical", "time", "title", "to_x", "to_y",
  "top1_share", "top_country", "top_k", "topic", "topic_id", "total",
  "total_articles", "total_citations", "total_collaborations",
  "total_mentions", "total_papers", "total_production", "trend",
  "trend_direction", "ts", "type", "type_label", "upper", "value",
  "value_cpy", "value_label", "value_norm", "value_num", "value_tc",
  "value_tp", "var", "variable", "variance", "weight", "weighted_citations",
  "weighted_degree", "where", "wilcox.test", "x", "x1", "x2", "xend",
  "xmax", "xmin", "y", "y1", "y2", "year", "year_factor", "yend", "ymax",
  "ymin", "zone"
))
